// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3JAKSM2-JJNZsAJDVUi72uD0RbVSz35s',
    appId: '1:56800720641:web:190e0120a40b31f338cd00',
    messagingSenderId: '56800720641',
    projectId: 'flightinfo-578a5',
    authDomain: 'flightinfo-578a5.firebaseapp.com',
    databaseURL: 'https://flightinfo-578a5-default-rtdb.firebaseio.com',
    storageBucket: 'flightinfo-578a5.appspot.com',
    measurementId: 'G-60FTT1QZDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpt3OULwXqSjR7F9Z-3jGni9yDM8bDPtA',
    appId: '1:56800720641:android:49bd25af3776b4e238cd00',
    messagingSenderId: '56800720641',
    projectId: 'flightinfo-578a5',
    databaseURL: 'https://flightinfo-578a5-default-rtdb.firebaseio.com',
    storageBucket: 'flightinfo-578a5.appspot.com',
  );
}
